### ISSUE TITLE
95!!

### ISSUE THREAD

**Issue by connorjclark** [exterkamp/lighthouseAll100s#1]
![image](https://user-images.githubusercontent.com/4071474/151842584-8113ed96-6b7d-4142-b80f-044f91d0f631.png)

**Comment by exterkamp** [comment]
Played with fonts a bit, we're back to 100's!

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/6392995/174186978-df9ba635-0047-45e0-9f6e-8e625f55d5ff.png">
